substitutions:
  _IMAGE_NAME: "site-processor"
  _SERVICE_NAME: "site-processor"

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:

  - id: "Fetch CI Templates"
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/green-energy-tracker-cloud/ci-cd-templates.git ci-template

  - id: "Trigger Child Pipeline"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud builds submit . \
          --config=ci-template/cloudbuild-template.yaml \
          --substitutions=_IMAGE_NAME="$_IMAGE_NAME",_SERVICE_NAME="$_SERVICE_NAME",_COMMIT_SHA="$COMMIT_SHA",_SHORT_SHA="$SHORT_SHA"